# Generated by Django 4.2.5 on 2023-09-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelobsidian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('username', models.CharField(db_column='Username', max_length=15, primary_key=True, serialize=False)),
                ('password', models.TextField(db_column='Password')),
            ],
            options={
                'db_table': 'admin_login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billing_id', models.AutoField(db_column='Billing_ID', primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, db_column='User_ID', max_length=15, null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('history', models.IntegerField(blank=True, db_column='History', null=True)),
            ],
            options={
                'db_table': 'billing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.IntegerField(db_column='Booking_ID', primary_key=True, serialize=False)),
                ('currentdate', models.DateField(blank=True, db_column='CurrentDate', null=True)),
                ('numberofdays', models.IntegerField(blank=True, db_column='NumberOfDays', null=True)),
                ('hasrated', models.TextField(blank=True, db_column='HasRated', null=True)),
                ('isbooked', models.TextField(blank=True, db_column='isBooked', null=True)),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cnic', models.CharField(db_column='CNIC', max_length=15, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=50, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=13, null=True)),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('password', models.TextField(db_column='Password')),
                ('paymenthistory', models.FloatField(blank=True, db_column='PaymentHistory', null=True)),
                ('answer1', models.TextField(blank=True, db_column='Answer1', null=True)),
                ('answer2', models.TextField(blank=True, db_column='Answer2', null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('branch_id', models.AutoField(db_column='Branch_ID', primary_key=True, serialize=False)),
                ('location', models.TextField(blank=True, db_column='Location', null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=13, null=True)),
            ],
            options={
                'db_table': 'hotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('food_id', models.AutoField(db_column='Food_ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('cuisine', models.TextField(blank=True, db_column='Cuisine', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
                ('image', models.TextField(blank=True, db_column='Image', null=True)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.IntegerField(blank=True, db_column='Food_ID', null=True)),
                ('billing_id', models.IntegerField(blank=True, db_column='Billing_ID', null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(db_column='Room_ID', primary_key=True, serialize=False)),
                ('roomnumber', models.IntegerField(db_column='RoomNumber')),
                ('isbooked', models.CharField(db_column='isBooked', max_length=5)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roomtype',
            fields=[
                ('roomtype_id', models.AutoField(db_column='RoomType_ID', primary_key=True, serialize=False)),
                ('numberofbeds', models.IntegerField(blank=True, db_column='NumberOfBeds', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
                ('image', models.TextField(blank=True, db_column='Image', null=True)),
                ('rating', models.FloatField(blank=True, db_column='Rating', null=True)),
                ('noofusersrated', models.IntegerField(blank=True, db_column='NoOfUsersRated', null=True)),
            ],
            options={
                'db_table': 'roomtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salesandoffers',
            fields=[
                ('offer_id', models.AutoField(db_column='Offer_ID', primary_key=True, serialize=False)),
                ('occasion', models.TextField(blank=True, db_column='Occasion', null=True)),
                ('percentage', models.FloatField(blank=True, db_column='Percentage', null=True)),
                ('image', models.TextField(blank=True, db_column='Image', null=True)),
            ],
            options={
                'db_table': 'salesandoffers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Securityquestions',
            fields=[
                ('question_id', models.AutoField(db_column='Question_ID', primary_key=True, serialize=False)),
                ('text', models.TextField(db_column='Text')),
            ],
            options={
                'db_table': 'securityquestions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Selectedoffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField(blank=True, db_column='Offer_ID', null=True)),
                ('billing_id', models.IntegerField(blank=True, db_column='Billing_ID', null=True)),
            ],
            options={
                'db_table': 'selectedoffers',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
