# Generated by Django 4.2.5 on 2023-10-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelobsidian', '0002_adminlogin_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Salesandoffers',
        ),
        migrations.DeleteModel(
            name='Securityquestions',
        ),
        migrations.DeleteModel(
            name='Selectedoffers',
        ),
    ]
