# Generated by Django 4.2.5 on 2023-10-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelobsidian', '0004_djangomigrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
