# Generated by Django 4.2.5 on 2023-10-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelobsidian', '0005_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
    ]
