# Generated by Django 4.2.5 on 2023-10-08 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelobsidian', '0007_alter_hotel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'managed': False},
        ),
    ]
